In [2]:
import numpy as np

# Векторные операции в numpy
## О чем речь?
В прошлой главе было показано, что `numpy` хорош в обращении с числами. Здесь же мы разберём чем он хорош на примере векторных операций.

Векторные операции - `ndarray` поддерживают element-wise, то есть, поэлементные, арифметические операции. Посмотрите следующий пример:

In [5]:
list_a = [10, 20, 30]
list_b = [1, 2, 3]

print('Результатом сложения объектов типа list будет конкатенация списков:')
print(f'lists: {list_a} + {list_b} = {list_a + list_b},\ttype(list_a + list_b): {type(list_a + list_b)},\tlen(list_a + list_b): {len(list_a + list_b)}')

arr_a, arr_b = np.array(list_a), np.array(list_b)
print('\nА вот ndarray складываются поэлементно:')
print(f'ndarrays: {arr_a} + {arr_b} = {arr_a + arr_b},\ttype(arr_a + arr_b): {type(arr_a + arr_b)},\tlen(arr_a + arr_b): {len(arr_a + arr_b)}')

Результатом сложения объектов типа list будет конкатенация списков:
lists: [10, 20, 30] + [1, 2, 3] = [10, 20, 30, 1, 2, 3],	type(list_a + list_b): <class 'list'>,	len(list_a + list_b): 6

А вот ndarray складываются поэлементно:
ndarrays: [10 20 30] + [1 2 3] = [11 22 33],	type(arr_a + arr_b): <class 'numpy.ndarray'>,	len(arr_a + arr_b): 3


Разумеется, к `ndarray` можно применять не только сложение, но и все остальные математические операции:

In [6]:
arr_a = np.array([10, 20, 30, 40])
arr_b = np.array([1, 2, 3, 4])

print(f'{arr_a} -  {arr_b} = {arr_a - arr_b }')
print(f'{arr_a} *  {arr_b} = {arr_a * arr_b }')
print(f'{arr_a} /  {arr_b} = {arr_a / arr_b }')
print(f'{arr_a} // {arr_b} = {arr_a // arr_b }')
print(f'{arr_a} %  {arr_b} = {arr_a % arr_b }')

bases = 2 * np.ones(4)
powers = np.arange(4)
print('\nМожно даже возводить в степень поэлементно: ')
print(f'{bases} ** {powers} = {bases ** powers}')

[10 20 30 40] -  [1 2 3 4] = [ 9 18 27 36]
[10 20 30 40] *  [1 2 3 4] = [ 10  40  90 160]
[10 20 30 40] /  [1 2 3 4] = [10. 10. 10. 10.]
[10 20 30 40] // [1 2 3 4] = [10 10 10 10]
[10 20 30 40] %  [1 2 3 4] = [0 0 0 0]

Можно даже возводить в степень поэлементно: 
[2. 2. 2. 2.] ** [0 1 2 3] = [1. 2. 4. 8.]


**NB: для матричного умножения используется оператор @**

Так же в качестве одного из операндов может выступать скаляр. 

In [7]:
arr_a = np.array([2, 4, 8, 16])
b = 5

print(f'{arr_a} +  {b} = {arr_a + b }')
print(f'{arr_a} -  {b} = {arr_a - b }')
print(f'{arr_a} *  {b} = {arr_a * b }')
print(f'{arr_a} /  {b} = {arr_a / b }')
print(f'{arr_a} // {b} = {arr_a // b }')
print(f'{arr_a} %  {b} = {arr_a % b }')
print(f'{arr_a} **  {b} = {arr_a ** b }')

[ 2  4  8 16] +  5 = [ 7  9 13 21]
[ 2  4  8 16] -  5 = [-3 -1  3 11]
[ 2  4  8 16] *  5 = [10 20 40 80]
[ 2  4  8 16] /  5 = [0.4 0.8 1.6 3.2]
[ 2  4  8 16] // 5 = [0 0 1 3]
[ 2  4  8 16] %  5 = [2 4 3 1]
[ 2  4  8 16] **  5 = [     32    1024   32768 1048576]


В более общем случае можно применять все вышеописанные арифметические операции между плоскими массивами и двухмерными и вообще между `ndarray` произвольных измерений.
Делает возможными такие операции трансляция массивов (array broadcasting). Вот правила, по которым она выполняется (не бойтесь, дальше будут примеры):
1. Если **размерность** двух массивов различается, форма (shape) массива с меньшей размерностью _дополняется_ единицами с левой стороны
1. Если форма двух массивов не сопадает в каком-то измерении, массив у которого форма в данном измерении == 1 дублируется вдоль этого измерения до соответствия формы другого массива
1. Если в каком либо измерении массивы различаются и количество элементов в этом измерении ни у одного из них не равно 1 - генерируется ошибка.

А теперь рассмотрим примеры на каждое правило

In [8]:
a = np.random.randint(10, size=5)
b = np.random.randint(10, size=(1, 1, 1, 5))
c = a + b
print('Правило 1: Если размерность двух массивов различается, форма (shape) массива с меньшей размерностью дополняется единицами с левой стороны.')

print(f'\na = {a}, a.shape = {a.shape} <--- не совпадает с b.shape')
print(f'b = {b}, b.shape = {b.shape}')
print(f'\nc = a + b = {a} + {b} = {c}, c.shape = {c.shape} <--- совпадает с b.shape')

print('\nНа самом деле, при попытке сложения произошло следующее: ')
print(f'c = a + b = np.broadcast_to(a, b.shape) + b = {np.broadcast_to(a, b.shape)} + {b} = {c}')

Правило 1: Если размерность двух массивов различается, форма (shape) массива с меньшей размерностью дополняется единицами с левой стороны.

a = [3 6 2 3 2], a.shape = (5,) <--- не совпадает с b.shape
b = [[[[3 1 1 6 3]]]], b.shape = (1, 1, 1, 5)

c = a + b = [3 6 2 3 2] + [[[[3 1 1 6 3]]]] = [[[[6 7 3 9 5]]]], c.shape = (1, 1, 1, 5) <--- совпадает с b.shape

На самом деле, при попытке сложения произошло следующее: 
c = a + b = np.broadcast_to(a, b.shape) + b = [[[[3 6 2 3 2]]]] + [[[[3 1 1 6 3]]]] = [[[[6 7 3 9 5]]]]


In [9]:
print('Правило 2: Если shape двух массивов не сопадает в каком-то измерении, массив у которого shape в данном измерении == 1 \nдублируется вдоль этого измерения до соответствия shape другого массива')

arr = np.random.randint(10, size=5)
k = 5
print('\nПример 1: Умножение 1-D массива на скаляр:')
print(f'k * arr = {k} * {arr} = {k*arr}, (k * arr).shape = {(k * arr).shape}')
print(f'По аналогии с предыдущим примером, k * arr = np.broadcast_to(k, arr.shape) * arr = {np.broadcast_to(k, arr.shape)} * {arr} = {k * arr}')

Правило 2: Если shape двух массивов не сопадает в каком-то измерении, массив у которого shape в данном измерении == 1 
дублируется вдоль этого измерения до соответствия shape другого массива

Пример 1: Умножение 1-D массива на скаляр:
k * arr = 5 * [4 8 8 4 8] = [20 40 40 20 40], (k * arr).shape = (5,)
По аналогии с предыдущим примером, k * arr = np.broadcast_to(k, arr.shape) * arr = [5 5 5 5 5] * [4 8 8 4 8] = [20 40 40 20 40]


In [10]:
matrix = np.random.randint(10, size=(4, 4))
vector = np.arange(4).reshape(1, 4)

print('\nПример 2: Сложение матрицы и вектора-строки:')
print(f'\nvector: \n{vector}')
print(f'\nmatrix: \n{matrix}')
print(f'\nvector + matrix (shape = {(vector + matrix).shape}): \n{vector + matrix}')

print('\nВ соответствии с правилом 2, если в одном из измерений не совпадают размеры: ')
print(f'vector shape = {vector.shape}')
print(f'matrix shape = {matrix.shape}')
print('В данном случае ^ это измерение 0')

print(f'\nЗначит, vector транслируется до matrix.shape дублируя единственную строку вдоль 0 измерения до соотвествия матрице.')
print(f'Получаестя, что vector + matrix это на самом деле np.broadcast_to(vector, matrix.shape) + matrix =')
print(f'{np.broadcast_to(vector, matrix.shape)}')
print('     +')
print(f'{matrix}')
print('     =')
print(f'{matrix + vector}')


Пример 2: Сложение матрицы и вектора-строки:

vector: 
[[0 1 2 3]]

matrix: 
[[7 2 3 6]
 [8 8 5 1]
 [8 5 8 9]
 [7 9 3 2]]

vector + matrix (shape = (4, 4)): 
[[ 7  3  5  9]
 [ 8  9  7  4]
 [ 8  6 10 12]
 [ 7 10  5  5]]

В соответствии с правилом 2, если в одном из измерений не совпадают размеры: 
vector shape = (1, 4)
matrix shape = (4, 4)
В данном случае ^ это измерение 0

Значит, vector транслируется до matrix.shape дублируя единственную строку вдоль 0 измерения до соотвествия матрице.
Получаестя, что vector + matrix это на самом деле np.broadcast_to(vector, matrix.shape) + matrix =
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
     +
[[7 2 3 6]
 [8 8 5 1]
 [8 5 8 9]
 [7 9 3 2]]
     =
[[ 7  3  5  9]
 [ 8  9  7  4]
 [ 8  6 10 12]
 [ 7 10  5  5]]


In [11]:
row = np.random.randint(10, size=(1, 5))
col = np.random.randint(10, size=(2, 1))

print('\nПример 3: Сложение вектора-столбца и вектора-строки:')
print(f'row (shape = {row.shape}): {row}')
print(f'col (shape = {col.shape}:\n {col}')

print(f'\nrow + col:\n {row + col}')

print('\nЗдесь ситуация похитрее. Оба массива транслируются в соответствии с правилом 2:')
print(f'\n             V вот здесь единица дополняется до {col.shape[0]}')
print(f'row.shape = {row.shape}')
print(f'col.shape = {col.shape} <-- а вот здесь до {row.shape[1]}')
print(f'\nОба массива принмают форму {(col.shape[0], row.shape[1])}')

print('\nВ итоге между собой складываются массивы: ')
mutual_shape = (col.shape[0], row.shape[1])
print(np.broadcast_to(row, mutual_shape))
print(f"{' '* mutual_shape[1]}+")
print(np.broadcast_to(col, mutual_shape))
print(f"{' '* mutual_shape[1]}=")
print(row + col)


Пример 3: Сложение вектора-столбца и вектора-строки:
row (shape = (1, 5)): [[5 9 0 3 7]]
col (shape = (2, 1):
 [[8]
 [8]]

row + col:
 [[13 17  8 11 15]
 [13 17  8 11 15]]

Здесь ситуация похитрее. Оба массива транслируются в соответствии с правилом 2:

             V вот здесь единица дополняется до 2
row.shape = (1, 5)
col.shape = (2, 1) <-- а вот здесь до 5

Оба массива принмают форму (2, 5)

В итоге между собой складываются массивы: 
[[5 9 0 3 7]
 [5 9 0 3 7]]
     +
[[8 8 8 8 8]
 [8 8 8 8 8]]
     =
[[13 17  8 11 15]
 [13 17  8 11 15]]


Правило номер три можете разобрать самостоятельно. Я же перейду к следующей теме

## Преимущества векторизации в производительности
Векторные операции `numpy` написаны на Си и потому очень быстры. Насколько они быстрее циклов предлагаю попробовать самостоятельно запустить следующие примеры один за другим.
Для отсчёта времени воспользуемся волшебной командой `%%timeit`. Сравним скорость вычисления скалярного произведения 2048 мерных векторов (да, такое приходится делать в ML)

In [12]:
v1 = np.random.rand(2048)
v2 = np.random.rand(2048)
list_1 = list(v1)
list_2 = list(v2)

In [13]:
%%timeit
list_3 = []
for i in range(len(list_1)):
    list_3.append(list_1[i] * list_2[i])
sum(list_3)

598 µs ± 10.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Можем чуть-чуть ускорить:

In [14]:
v1 = np.random.rand(2048)
v2 = np.random.rand(2048)
list_1 = list(v1)
list_2 = list(v2)

In [15]:
%%timeit
product = 0
for x, y in zip(list_1, list_2):
    product += x*y

446 µs ± 10.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Однако это всё-равно на **порядки** отстаёт от производительность `numpy`

In [ ]:
v1 = np.random.rand(2048)
v2 = np.random.rand(2048)

In [ ]:
%%timeit
np.sum(v1 * v2)